### ISSUE TITLE
Can’t migrate time type

### ISSUE THREAD

**Issue by guofei** [datastax/cassandra-data-migrator#63]
## Version
Cassandra 3.11.10
Spark 2.4.8
cassandra-data-migrate 2.10.3

## Origin table
```
CREATE TYPE ks.myty (
  a int,
  b text
);

CREATE TABLE ks.tb (
   id int PRIMARY KEY, 
   tt text,
   bg bigint,
   db double,
   tm time,
   mp map<int, text>,
   lt list<text>,
   bb blob,
   st set<int>,
   uu uuid,
   bn boolean,
   tp tuple<int, int>,
   ft float,
   tn tinyint,
   dc decimal,
   dt date,
   ut myty,
   vi varint
);

INSERT INTO ks.tb (id, tt, bg, db, tm, mp, lt, bb, st, uu, bn, tp, ft, tn, dc, dt, ut, vi) VALUES (
  1, 
  'text', 
  1000000000, 
  1.2, 
  '08:12:54', 
  {1:'a'},
  ['a', 'b'],
  bigintAsBlob(123),
  {1,2,3},
  now(),
  true,
  (1,1),
  1.1,
  1,
  12,
  '2011-02-03',
  {a: 1, b: 'b'},
  0
);
```

## Target table
The target table is the same as the origin table.

## sparkConf.properties
```
spark.query.origin                                id,tt,bg,db,tm,mp,lt,bb,st,uu,bn,tp,ft,tn,dc,dt,ut,vi
spark.query.origin.partitionKey                   id
spark.query.target.id                             id
spark.query.types                                 1,0,2,3,4,5%1%0,6%0,7,8%1,9,10,11,12,13,14,15,16,17
```

## Error
```
23/02/06 11:37:27 ERROR CopyJobSession: Error occurred retry#: 1
com.datastax.oss.driver.api.core.type.codec.CodecNotFoundException: Codec not found for requested operation: [TIME <-> java.time.LocalDate]
        at com.datastax.oss.driver.internal.core.type.codec.registry.CachingCodecRegistry.createCodec(CachingCodecRegistry.java:609)
        at com.datastax.oss.driver.internal.core.type.codec.registry.DefaultCodecRegistry$1.load(DefaultCodecRegistry.java:95)
        at com.datastax.oss.driver.internal.core.type.codec.registry.DefaultCodecRegistry$1.load(DefaultCodecRegistry.java:92)
        at com.datastax.oss.driver.shaded.guava.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
        at com.datastax.oss.driver.shaded.guava.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2276)
        at com.datastax.oss.driver.shaded.guava.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
        at com.datastax.oss.driver.shaded.guava.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
        at com.datastax.oss.driver.shaded.guava.common.cache.LocalCache.get(LocalCache.java:3951)
        at com.datastax.oss.driver.shaded.guava.common.cache.LocalCache.getOrLoad(LocalCache.java:3973)
        at com.datastax.oss.driver.shaded.guava.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957)
        at com.datastax.oss.driver.shaded.guava.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4963)
        at com.datastax.oss.driver.internal.core.type.codec.registry.DefaultCodecRegistry.getCachedCodec(DefaultCodecRegistry.java:117)
        at com.datastax.oss.driver.internal.core.type.codec.registry.CachingCodecRegistry.codecFor(CachingCodecRegistry.java:215)
        at com.datastax.oss.driver.api.core.data.GettableByIndex.get(GettableByIndex.java:126)
        at datastax.astra.migrate.BaseJobSession.getData(BaseJobSession.java:95)
        at datastax.astra.migrate.AbstractJobSession.bindInsert(AbstractJobSession.java:194)
        at datastax.astra.migrate.CopyJobSession.getDataAndInsert(CopyJobSession.java:121)
        at datastax.astra.migrate.Migrate$$anonfun$migrateTable$1$$anonfun$apply$1$$anonfun$apply$2.apply(Migrate.scala:29)
        at datastax.astra.migrate.Migrate$$anonfun$migrateTable$1$$anonfun$apply$1$$anonfun$apply$2.apply(Migrate.scala:27)
        at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$withSessionDo$1.apply(CassandraConnector.scala:105)
        at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$withSessionDo$1.apply(CassandraConnector.scala:104)
        at com.datastax.spark.connector.cql.CassandraConnector.closeResourceAfterUse(CassandraConnector.scala:122)
        at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:104)
        at datastax.astra.migrate.Migrate$$anonfun$migrateTable$1$$anonfun$apply$1.apply(Migrate.scala:27)
        at datastax.astra.migrate.Migrate$$anonfun$migrateTable$1$$anonfun$apply$1.apply(Migrate.scala:26)
        at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$withSessionDo$1.apply(CassandraConnector.scala:105)
        at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$withSessionDo$1.apply(CassandraConnector.scala:104)
        at com.datastax.spark.connector.cql.CassandraConnector.closeResourceAfterUse(CassandraConnector.scala:122)
        at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:104)
        at datastax.astra.migrate.Migrate$$anonfun$migrateTable$1.apply(Migrate.scala:26)
        at datastax.astra.migrate.Migrate$$anonfun$migrateTable$1.apply(Migrate.scala:25)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
        at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$27.apply(RDD.scala:972)
        at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$27.apply(RDD.scala:972)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2107)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2107)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:123)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:411)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:417)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
```

## Other info
After I add a new type like this:
```
diff --git a/src/main/java/datastax/astra/migrate/MigrateDataType.java b/src/main/java/datastax/astra/migrate/MigrateDataType.java
index cd324e0..f176aba 100644
--- a/src/main/java/datastax/astra/migrate/MigrateDataType.java
+++ b/src/main/java/datastax/astra/migrate/MigrateDataType.java
@@ -8,6 +8,7 @@ import java.math.BigInteger;
 import java.nio.ByteBuffer;
 import java.time.Instant;
 import java.time.LocalDate;
+import java.time.LocalTime;
 import java.util.*;

 public class MigrateDataType {
@@ -81,6 +82,8 @@ public class MigrateDataType {
                 return UdtValue.class;
             case 17:
                 return BigInteger.class;
+            case 18:
+                return LocalTime.class;
         }

         return Object.class;
```

And change sparkConf.properties like this:
```
spark.query.origin                                id,tt,bg,db,tm,mp,lt,bb,st,uu,bn,tp,ft,tn,dc,dt,ut,vi
spark.query.origin.partitionKey                   id
spark.query.target.id                             id
spark.query.types                                 1,0,2,3,18,5%1%0,6%0,7,8%1,9,10,11,12,13,14,15,16,17
```

It migrates successfully.

**Comment by guofei** [comment]
I found this document that said `time` type is converted to `java.time.LocalTime` 

https://docs.datastax.com/en/developer/java-driver/4.10/manual/core/temporal_types/

CQL | Java |  
-- | -- | --
date | java.time.LocalDate |  
time | java.time.LocalTime |  
timestamp | java.time.Instant | No time zone. Use Instant.atZone or register TypeCodecs.ZONED_TIMESTAMP_SYSTEM, TypeCodecs.ZONED_TIMESTAMP_UTC or TypeCodecs.zonedTimestampAt()
duration | CqlDuration | Custom driver type; can’t be accurately represented by any of the java.time types.
